### ISSUE TITLE
Criar endpoint para retornar lista de cores do usuário - Backend

### ISSUE THREAD

**Issue by cp-operacional** [cp-operacional/authprojectbackend#15]

**Comment by cp-operacional** [comment]
Endpoint deve serguir esse formato:

resources/{id}/

deve retornar uma lista de objetos, no qual são as cores do usuário de id selecionado do endpoint

já existe a função get_queryset em views.py de resources, se baseie nela.

**Comment by jmarcosbs** [comment]
Endpoint criado, não precisa passar o id do usuário, quando for feita chamada no endpoint "resources/" vai identificar o usuário que está requisitando e a resposta será uma lista de resources daquele usuário.

**Comment by jmarcosbs** [comment]
Dar merge na branch **endpoint-to-user-colors**
